spring:
    application:
        name: DesafioLogin
    datasource:
        username: 
        password: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/desafio
    jpa:
        hibernate.ddlAuto: update 

api:
    security:
        token:
            secret: "${JWT_SECRET:my-secret-key}"
