spring:
    application:
        name: DesafioLogin
    datasource:
        username: 
        password: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/desafio
